config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  root to: "ques#index"
  
  resources :ques do
    resources :services
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :ques, dependent: :destroy
  has_many :services, through: :ques

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/que.rb
class Que < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :que
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/managers/confirmations_controller.rb
# frozen_string_literal: true

class Managers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/managers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/managers/passwords_controller.rb
# frozen_string_literal: true

class Managers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/registrations_controller.rb
# frozen_string_literal: true

class Managers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/managers/sessions_controller.rb
# frozen_string_literal: true

class Managers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/managers/unlocks_controller.rb
# frozen_string_literal: true

class Managers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
    before_action :authenticate_manager!
    # before_action :authenticate_manager!, only: [:edit, :update, :destroy, :create, :new]
    
    def index
        @ques = current_manager.ques  
    end

    def show
        @que = current_manager.ques.find(params[:id])   
    end

    def new
        @que = current_manager.ques.new    
    end

    def create
        @que = current_manager.ques.create(que_params)  
        redirect_to que_path(@que)
    end

    def destroy
        @que = current_manager.ques.find(params[:id])
        @que.destroy
        redirect_to ques_path    
    end

    def edit
        @que = current_manager.ques.find(params[:id])  
    end

    def update
        @que = current_manager.ques.find(params[:id])
        @que.update(que_params)
        redirect_to que_path(@que)    
    end

    private
    def que_params
        params.require(:que).permit(:name, :email, :location, :img)    
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :authenticate_manager!
    def new
        @que = current_manager.ques.find(params[:que_id])
        @service = @que.services.new
    end

    def create
        @que = current_manager.ques.find(params[:que_id])
        @service = @que.services.create(service_params)
        redirect_to que_path(@que)
    end

    def show
        @que = current_manager.ques.find(params[:que_id])    
    end

    def edit
        @que = current_manager.ques.find(params[:que_id])
    end

    def update
        @que.services.update(que_params)
        redirect_to que_path(@que)   
    end
    
    def destroy
        @que = current_manager.find(params[:que_id])
        @service = @que.services.find(params[:que_id])
        @service.destroy
        redirect_to que_path(@que)    
    end

    private
    def service_params
        params.require(:service).permit(:name,:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# Devise alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="nav">
      <%if manager_signed_in?%>
      <%= "Hello #{current_manager.email}"%>
      <%= link_to "Ques", ques_path%>|
      <%= link_to "Edit user", edit_manager_registration_path%>|
      <%= link_to "Sign out", destroy_manager_session_path, method: :delete%>|
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/ques/create.html.erb
<h1>Ques#create</h1>
<p>Find me in app/views/ques/create.html.erb</p>

app/views/ques/edit.html.erb
<h1>Ques#edit</h1>
<p>Find me in app/views/ques/edit.html.erb</p>

app/views/ques/index.html.erb
<h4><%= link_to "add Que", new_que_path%></h4>
<h1>Your Queues</h1>
<% @ques.each do |que| %>
    <%= link_to que.name, que_path(que)%>
    <br>
<% end %>

app/views/ques/new.html.erb
<%= form_with scope: :que, url: ques_path, local: true do |form| %>
  <p>
    <%= form.label :"Queue name" %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :"email" %><br>
    <%= form.text_area :email %>
  </p>

  <p>
    <%= form.label :"location" %><br>
    <%= form.text_area :location %>
  </p>

  <p>
    <%= form.label :"image" %><br>
    <%= form.text_area :img %>
  </p>
  
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/ques/show.html.erb
<br>
<%= link_to "Delete Que", que_path(@que), method: :delete%>
<%= link_to "Edit Que", edit_que_path(@que)%>
<%= link_to "Add Service", new_que_service_path(@que)%>

<h1><%=@que.name%></h1>
<br>
<img src="<%= @que.img%>">
<h3><%=@que.email%>, <%=@que.location%></h3>

<% @que.services.each do |service|%>
    <%= service.name %>:
    <br>
    <%= service.description%>
    <br>
    <br>
<% end %>
<br>

app/views/ques/update.html.erb
<h1>Ques#update</h1>
<p>Find me in app/views/ques/update.html.erb</p>

app/views/services/new.html.erb
<%= form_for @que.services.new, url: {action: "create"}, local: true do |form| %>
  <p>
    <%= form.label :"Service name" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :"Description" %><br>
    <%= form.text_area :description %>
  </p>
  
 
  <p>
    <%= form.submit %>
  </p>
<% end %>